- name: mysql
  hosts: mysql
  become: yes
  tasks:
  - name: disable old mysql 
    ansible.builtin.shell: dnf module disable mysql 

  - name: copy mysql repo file
    ansible.builtin.copy:
    src: mysql.repo
    dest: /etc/yum.repos.d/mysql.repo

  - name: install mysql
    ansible.builtin.dng: dnf install mysql-community-server -y
      name: mysql-community-server
      state: present

  - name: start and enable mysql
    ansible.builtin.service:
    state: started
    enabled: yes

  - name: set root password
    ansible.builtin.command: mysql_secure_installation --set-root-pass RoboShop@1: 

   